spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.mongodb.uri=mongodb://localhost:27017/ai_llm_db
spring.mongodb.username=chetana
spring.mongodb.password=chetana

spring.profiles.active = dev

spring.datasource.generate-unique-name= true
