spring.ai.openai.api-key= sk-proj-xxxxxxxxxxxxxxxx
spring.mongodb.uri=mongodb://localhost:27017/ai_llm_db
spring.mongodb.username=chetana
spring.mongodb.password=chetana

spring.profiles.active = dev

spring.datasource.generate-unique-name= true
