spring.ai.openai.api-key=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

spring.mongodb.uri=mongodb://localhost:27017/ai_llm_db
spring.mongodb.username=chetana
spring.mongodb.password=chetana

spring.profiles.active = dev

spring.datasource.generate-unique-name= true
